# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1fb6151929eb0b6549518b068e111412"
application_url = "https://nova-strengths-his-jacksonville.trycloudflare.com"
embedded = true
name = "open-hours"
handle = "open-hours-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nova-strengths-his-jacksonville.trycloudflare.com/auth/callback",
  "https://nova-strengths-his-jacksonville.trycloudflare.com/auth/shopify/callback",
  "https://nova-strengths-his-jacksonville.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
